#ifndef MCU_HW_H
#define MCU_HW_H

#include "Std_Types.h"

/********************************DIO*********************************************/

	/*	PORT PORTS BASE ADDRESSES (APB)	*/
#define		PORTA_BaseAddress		0x40004000	
#define		PORTB_BaseAddress		0x40005000
#define		PORTC_BaseAddress		0x40006000
#define		PORTD_BaseAddress		0x40007000	
#define		PORTE_BaseAddress		0x40024000
#define		PORTF_BaseAddress		0x40025000


#define	GPIOA_DATA					*((volatile u32 *)(PORTA_BaseAddress+0x3FC))
#define	GPIOA_DIR					*((volatile u32 *)(PORTA_BaseAddress+0x400))
#define	GPIOA_IS					*((volatile u32 *)(PORTA_BaseAddress+0x404))
#define	GPIOA_IBE					*((volatile u32 *)(PORTA_BaseAddress+0x408))
#define	GPIOA_IEV					*((volatile u32 *)(PORTA_BaseAddress+0x40C))
#define	GPIOA_IM					*((volatile u32 *)(PORTA_BaseAddress+0x410))
#define	GPIOA_RIS					*((volatile u32 *)(PORTA_BaseAddress+0x414))
#define	GPIOA_MIS					*((volatile u32 *)(PORTA_BaseAddress+0x418))
#define	GPIOA_ICR					*((volatile u32 *)(PORTA_BaseAddress+0x41C))
#define	GPIOA_AFSEL					*((volatile u32 *)(PORTA_BaseAddress+0x420))
#define	GPIOA_DR2R					*((volatile u32 *)(PORTA_BaseAddress+0x500))
#define	GPIOA_DR4R					*((volatile u32 *)(PORTA_BaseAddress+0x504))
#define	GPIOA_DR8R					*((volatile u32 *)(PORTA_BaseAddress+0x508))
#define	GPIOA_ODR					*((volatile u32 *)(PORTA_BaseAddress+0x50C))
#define	GPIOA_PUR					*((volatile u32 *)(PORTA_BaseAddress+0x510))
#define	GPIOA_PDR					*((volatile u32 *)(PORTA_BaseAddress+0x514))
#define	GPIOA_SLR					*((volatile u32 *)(PORTA_BaseAddress+0x518))
#define	GPIOA_DEN					*((volatile u32 *)(PORTA_BaseAddress+0x51C))
#define	GPIOA_LOCK					*((volatile u32 *)(PORTA_BaseAddress+0x520))
#define	GPIOA_AMSEL					*((volatile u32 *)(PORTA_BaseAddress+0x528))
#define	GPIOA_PCTL					*((volatile u32 *)(PORTA_BaseAddress+0x52C))
#define	GPIOA_ADCCTL				*((volatile u32 *)(PORTA_BaseAddress+0x530))
#define	GPIOA_DMACTL				*((volatile u32 *)(PORTA_BaseAddress+0x534))
#define	GPIOA_PeriphID4				*((volatile u32 *)(PORTA_BaseAddress+0xFD0))
#define	GPIOA_PeriphID5				*((volatile u32 *)(PORTA_BaseAddress+0xFD4))
#define	GPIOA_PeriphID6				*((volatile u32 *)(PORTA_BaseAddress+0xFD8))
#define	GPIOA_PeriphID7				*((volatile u32 *)(PORTA_BaseAddress+0xFDC))
#define	GPIOA_PeriphID0				*((volatile u32 *)(PORTA_BaseAddress+0xFE0))
#define	GPIOA_PeriphID1				*((volatile u32 *)(PORTA_BaseAddress+0xFE4))
#define	GPIOA_PeriphID2				*((volatile u32 *)(PORTA_BaseAddress+0xFE8))
#define	GPIOA_PeriphID3				*((volatile u32 *)(PORTA_BaseAddress+0xFEC))
#define	GPIOA_PCellID0				*((volatile u32 *)(PORTA_BaseAddress+0xFF0))
#define	GPIOA_PCellID1				*((volatile u32 *)(PORTA_BaseAddress+0xFF4))
#define	GPIOA_PCellID2				*((volatile u32 *)(PORTA_BaseAddress+0xFF8))
#define	GPIOA_PCellID3				*((volatile u32 *)(PORTA_BaseAddress+0xFFC))


#define	GPIOB_DATA				     *((volatile u32 *)(PORTB_BaseAddress+0x3FC))
#define	GPIOB_DIR				     *((volatile u32 *)(PORTB_BaseAddress+0x400))
#define	GPIOB_IS				     *((volatile u32 *)(PORTB_BaseAddress+0x404))
#define	GPIOB_IBE				     *((volatile u32 *)(PORTB_BaseAddress+0x408))
#define	GPIOB_IEV				     *((volatile u32 *)(PORTB_BaseAddress+0x40C))
#define	GPIOB_IM				     *((volatile u32 *)(PORTB_BaseAddress+0x410))
#define	GPIOB_RIS				     *((volatile u32 *)(PORTB_BaseAddress+0x414))
#define	GPIOB_MIS				     *((volatile u32 *)(PORTB_BaseAddress+0x418))
#define	GPIOB_ICR				     *((volatile u32 *)(PORTB_BaseAddress+0x41C))
#define	GPIOB_AFSEL				     *((volatile u32 *)(PORTB_BaseAddress+0x420))
#define	GPIOB_DR2R				     *((volatile u32 *)(PORTB_BaseAddress+0x500))
#define	GPIOB_DR4R				     *((volatile u32 *)(PORTB_BaseAddress+0x504))
#define	GPIOB_DR8R				     *((volatile u32 *)(PORTB_BaseAddress+0x508))
#define	GPIOB_ODR				     *((volatile u32 *)(PORTB_BaseAddress+0x50C))
#define	GPIOB_PUR				     *((volatile u32 *)(PORTB_BaseAddress+0x510))
#define	GPIOB_PDR				     *((volatile u32 *)(PORTB_BaseAddress+0x514))
#define	GPIOB_SLR				     *((volatile u32 *)(PORTB_BaseAddress+0x518))
#define	GPIOB_DEN				     *((volatile u32 *)(PORTB_BaseAddress+0x51C))
#define	GPIOB_LOCK				     *((volatile u32 *)(PORTB_BaseAddress+0x520))
#define	GPIOB_AMSEL				     *((volatile u32 *)(PORTB_BaseAddress+0x528))
#define	GPIOB_PCTL				     *((volatile u32 *)(PORTB_BaseAddress+0x52C))
#define	GPIOB_ADCCTL			     *((volatile u32 *)(PORTB_BaseAddress+0x530))
#define	GPIOB_DMACTL			     *((volatile u32 *)(PORTB_BaseAddress+0x534))
#define	GPIOB_PeriphID4			     *((volatile u32 *)(PORTB_BaseAddress+0xFD0))
#define	GPIOB_PeriphID5			     *((volatile u32 *)(PORTB_BaseAddress+0xFD4))
#define	GPIOB_PeriphID6			     *((volatile u32 *)(PORTB_BaseAddress+0xFD8))
#define	GPIOB_PeriphID7			     *((volatile u32 *)(PORTB_BaseAddress+0xFDC))
#define	GPIOB_PeriphID0			     *((volatile u32 *)(PORTB_BaseAddress+0xFE0))
#define	GPIOB_PeriphID1			     *((volatile u32 *)(PORTB_BaseAddress+0xFE4))
#define	GPIOB_PeriphID2			     *((volatile u32 *)(PORTB_BaseAddress+0xFE8))
#define	GPIOB_PeriphID3			     *((volatile u32 *)(PORTB_BaseAddress+0xFEC))
#define	GPIOB_PCellID0			     *((volatile u32 *)(PORTB_BaseAddress+0xFF0))
#define	GPIOB_PCellID1			     *((volatile u32 *)(PORTB_BaseAddress+0xFF4))
#define	GPIOB_PCellID2			     *((volatile u32 *)(PORTB_BaseAddress+0xFF8))
#define	GPIOB_PCellID3			     *((volatile u32 *)(PORTB_BaseAddress+0xFFC))


#define	GPIOC_DATA					 *((volatile u32 *)(PORTC_BaseAddress+0x3FC))
#define	GPIOC_DIR					 *((volatile u32 *)(PORTC_BaseAddress+0x400))
#define	GPIOC_IS					 *((volatile u32 *)(PORTC_BaseAddress+0x404))
#define	GPIOC_IBE					 *((volatile u32 *)(PORTC_BaseAddress+0x408))
#define	GPIOC_IEV					 *((volatile u32 *)(PORTC_BaseAddress+0x40C))
#define	GPIOC_IM					 *((volatile u32 *)(PORTC_BaseAddress+0x410))
#define	GPIOC_RIS					 *((volatile u32 *)(PORTC_BaseAddress+0x414))
#define	GPIOC_MIS					 *((volatile u32 *)(PORTC_BaseAddress+0x418))
#define	GPIOC_ICR					 *((volatile u32 *)(PORTC_BaseAddress+0x41C))
#define	GPIOC_AFSEL					 *((volatile u32 *)(PORTC_BaseAddress+0x420))
#define	GPIOC_DR2R					 *((volatile u32 *)(PORTC_BaseAddress+0x500))
#define	GPIOC_DR4R					 *((volatile u32 *)(PORTC_BaseAddress+0x504))
#define	GPIOC_DR8R					 *((volatile u32 *)(PORTC_BaseAddress+0x508))
#define	GPIOC_ODR					 *((volatile u32 *)(PORTC_BaseAddress+0x50C))
#define	GPIOC_PUR					 *((volatile u32 *)(PORTC_BaseAddress+0x510))
#define	GPIOC_PDR					 *((volatile u32 *)(PORTC_BaseAddress+0x514))
#define	GPIOC_SLR					 *((volatile u32 *)(PORTC_BaseAddress+0x518))
#define	GPIOC_DEN					 *((volatile u32 *)(PORTC_BaseAddress+0x51C))
#define	GPIOC_LOCK					 *((volatile u32 *)(PORTC_BaseAddress+0x520))
#define	GPIOC_AMSEL					 *((volatile u32 *)(PORTC_BaseAddress+0x528))
#define	GPIOC_PCTL					 *((volatile u32 *)(PORTC_BaseAddress+0x52C))
#define	GPIOC_ADCCTL				 *((volatile u32 *)(PORTC_BaseAddress+0x530))
#define	GPIOC_DMACTL				 *((volatile u32 *)(PORTC_BaseAddress+0x534))
#define	GPIOC_PeriphID4				 *((volatile u32 *)(PORTC_BaseAddress+0xFD0))
#define	GPIOC_PeriphID5				 *((volatile u32 *)(PORTC_BaseAddress+0xFD4))
#define	GPIOC_PeriphID6				 *((volatile u32 *)(PORTC_BaseAddress+0xFD8))
#define	GPIOC_PeriphID7				 *((volatile u32 *)(PORTC_BaseAddress+0xFDC))
#define	GPIOC_PeriphID0				 *((volatile u32 *)(PORTC_BaseAddress+0xFE0))
#define	GPIOC_PeriphID1				 *((volatile u32 *)(PORTC_BaseAddress+0xFE4))
#define	GPIOC_PeriphID2				 *((volatile u32 *)(PORTC_BaseAddress+0xFE8))
#define	GPIOC_PeriphID3				 *((volatile u32 *)(PORTC_BaseAddress+0xFEC))
#define	GPIOC_PCellID0				 *((volatile u32 *)(PORTC_BaseAddress+0xFF0))
#define	GPIOC_PCellID1				 *((volatile u32 *)(PORTC_BaseAddress+0xFF4))
#define	GPIOC_PCellID2				 *((volatile u32 *)(PORTC_BaseAddress+0xFF8))
#define	GPIOC_PCellID3				 *((volatile u32 *)(PORTC_BaseAddress+0xFFC))


#define	GPIOD_DATA					  *((volatile u32 *)(PORTD_BaseAddress+0x3FC))
#define	GPIOD_DIR					  *((volatile u32 *)(PORTD_BaseAddress+0x400))
#define	GPIOD_IS					  *((volatile u32 *)(PORTD_BaseAddress+0x404))
#define	GPIOD_IBE					  *((volatile u32 *)(PORTD_BaseAddress+0x408))
#define	GPIOD_IEV					  *((volatile u32 *)(PORTD_BaseAddress+0x40C))
#define	GPIOD_IM					  *((volatile u32 *)(PORTD_BaseAddress+0x410))
#define	GPIOD_RIS					  *((volatile u32 *)(PORTD_BaseAddress+0x414))
#define	GPIOD_MIS					  *((volatile u32 *)(PORTD_BaseAddress+0x418))
#define	GPIOD_ICR					  *((volatile u32 *)(PORTD_BaseAddress+0x41C))
#define	GPIOD_AFSEL					  *((volatile u32 *)(PORTD_BaseAddress+0x420))
#define	GPIOD_DR2R					  *((volatile u32 *)(PORTD_BaseAddress+0x500))
#define	GPIOD_DR4R					  *((volatile u32 *)(PORTD_BaseAddress+0x504))
#define	GPIOD_DR8R					  *((volatile u32 *)(PORTD_BaseAddress+0x508))
#define	GPIOD_ODR					  *((volatile u32 *)(PORTD_BaseAddress+0x50C))
#define	GPIOD_PUR					  *((volatile u32 *)(PORTD_BaseAddress+0x510))
#define	GPIOD_PDR					  *((volatile u32 *)(PORTD_BaseAddress+0x514))
#define	GPIOD_SLR					  *((volatile u32 *)(PORTD_BaseAddress+0x518))
#define	GPIOD_DEN					  *((volatile u32 *)(PORTD_BaseAddress+0x51C))
#define	GPIOD_LOCK					  *((volatile u32 *)(PORTD_BaseAddress+0x520))
#define	GPIOD_AMSEL					  *((volatile u32 *)(PORTD_BaseAddress+0x528))
#define	GPIOD_PCTL					  *((volatile u32 *)(PORTD_BaseAddress+0x52C))
#define	GPIOD_ADCCTL				  *((volatile u32 *)(PORTD_BaseAddress+0x530))
#define	GPIOD_DMACTL				  *((volatile u32 *)(PORTD_BaseAddress+0x534))
#define	GPIOD_PeriphID4				  *((volatile u32 *)(PORTD_BaseAddress+0xFD0))
#define	GPIOD_PeriphID5				  *((volatile u32 *)(PORTD_BaseAddress+0xFD4))
#define	GPIOD_PeriphID6				  *((volatile u32 *)(PORTD_BaseAddress+0xFD8))
#define	GPIOD_PeriphID7				  *((volatile u32 *)(PORTD_BaseAddress+0xFDC))
#define	GPIOD_PeriphID0				  *((volatile u32 *)(PORTD_BaseAddress+0xFE0))
#define	GPIOD_PeriphID1				  *((volatile u32 *)(PORTD_BaseAddress+0xFE4))
#define	GPIOD_PeriphID2				  *((volatile u32 *)(PORTD_BaseAddress+0xFE8))
#define	GPIOD_PeriphID3				  *((volatile u32 *)(PORTD_BaseAddress+0xFEC))
#define	GPIOD_PCellID0				  *((volatile u32 *)(PORTD_BaseAddress+0xFF0))
#define	GPIOD_PCellID1				  *((volatile u32 *)(PORTD_BaseAddress+0xFF4))
#define	GPIOD_PCellID2				  *((volatile u32 *)(PORTD_BaseAddress+0xFF8))
#define	GPIOD_PCellID3				  *((volatile u32 *)(PORTD_BaseAddress+0xFFC))


#define	GPIOE_DATA					   *((volatile u32 *)(PORTE_BaseAddress+0x3FC))
#define	GPIOE_DIR					   *((volatile u32 *)(PORTE_BaseAddress+0x400))
#define	GPIOE_IS					   *((volatile u32 *)(PORTE_BaseAddress+0x404))
#define	GPIOE_IBE					   *((volatile u32 *)(PORTE_BaseAddress+0x408))
#define	GPIOE_IEV					   *((volatile u32 *)(PORTE_BaseAddress+0x40C))
#define	GPIOE_IM					   *((volatile u32 *)(PORTE_BaseAddress+0x410))
#define	GPIOE_RIS					   *((volatile u32 *)(PORTE_BaseAddress+0x414))
#define	GPIOE_MIS					   *((volatile u32 *)(PORTE_BaseAddress+0x418))
#define	GPIOE_ICR					   *((volatile u32 *)(PORTE_BaseAddress+0x41C))
#define	GPIOE_AFSEL					   *((volatile u32 *)(PORTE_BaseAddress+0x420))
#define	GPIOE_DR2R					   *((volatile u32 *)(PORTE_BaseAddress+0x500))
#define	GPIOE_DR4R					   *((volatile u32 *)(PORTE_BaseAddress+0x504))
#define	GPIOE_DR8R					   *((volatile u32 *)(PORTE_BaseAddress+0x508))
#define	GPIOE_ODR					   *((volatile u32 *)(PORTE_BaseAddress+0x50C))
#define	GPIOE_PUR					   *((volatile u32 *)(PORTE_BaseAddress+0x510))
#define	GPIOE_PDR					   *((volatile u32 *)(PORTE_BaseAddress+0x514))
#define	GPIOE_SLR					   *((volatile u32 *)(PORTE_BaseAddress+0x518))
#define	GPIOE_DEN					   *((volatile u32 *)(PORTE_BaseAddress+0x51C))
#define	GPIOE_LOCK					   *((volatile u32 *)(PORTE_BaseAddress+0x520))
#define	GPIOE_AMSEL					   *((volatile u32 *)(PORTE_BaseAddress+0x528))
#define	GPIOE_PCTL					   *((volatile u32 *)(PORTE_BaseAddress+0x52C))
#define	GPIOE_ADCCTL				   *((volatile u32 *)(PORTE_BaseAddress+0x530))
#define	GPIOE_DMACTL				   *((volatile u32 *)(PORTE_BaseAddress+0x534))
#define	GPIOE_PeriphID4				   *((volatile u32 *)(PORTE_BaseAddress+0xFD0))
#define	GPIOE_PeriphID5				   *((volatile u32 *)(PORTE_BaseAddress+0xFD4))
#define	GPIOE_PeriphID6				   *((volatile u32 *)(PORTE_BaseAddress+0xFD8))
#define	GPIOE_PeriphID7				   *((volatile u32 *)(PORTE_BaseAddress+0xFDC))
#define	GPIOE_PeriphID0				   *((volatile u32 *)(PORTE_BaseAddress+0xFE0))
#define	GPIOE_PeriphID1				   *((volatile u32 *)(PORTE_BaseAddress+0xFE4))
#define	GPIOE_PeriphID2				   *((volatile u32 *)(PORTE_BaseAddress+0xFE8))
#define	GPIOE_PeriphID3				   *((volatile u32 *)(PORTE_BaseAddress+0xFEC))
#define	GPIOE_PCellID0				   *((volatile u32 *)(PORTE_BaseAddress+0xFF0))
#define	GPIOE_PCellID1				   *((volatile u32 *)(PORTE_BaseAddress+0xFF4))
#define	GPIOE_PCellID2				   *((volatile u32 *)(PORTE_BaseAddress+0xFF8))
#define	GPIOE_PCellID3				   *((volatile u32 *)(PORTE_BaseAddress+0xFFC))


#define	GPIOF_DATA					   *((volatile u32 *)(PORTF_BaseAddress+0x3FC))
#define	GPIOF_DIR					   *((volatile u32 *)(PORTF_BaseAddress+0x400))
#define	GPIOF_IS					   *((volatile u32 *)(PORTF_BaseAddress+0x404))
#define	GPIOF_IBE					   *((volatile u32 *)(PORTF_BaseAddress+0x408))
#define	GPIOF_IEV					   *((volatile u32 *)(PORTF_BaseAddress+0x40C))
#define	GPIOF_IM					   *((volatile u32 *)(PORTF_BaseAddress+0x410))
#define	GPIOF_RIS					   *((volatile u32 *)(PORTF_BaseAddress+0x414))
#define	GPIOF_MIS					   *((volatile u32 *)(PORTF_BaseAddress+0x418))
#define	GPIOF_ICR					   *((volatile u32 *)(PORTF_BaseAddress+0x41C))
#define	GPIOF_AFSEL					   *((volatile u32 *)(PORTF_BaseAddress+0x420))
#define	GPIOF_DR2R					   *((volatile u32 *)(PORTF_BaseAddress+0x500))
#define	GPIOF_DR4R					   *((volatile u32 *)(PORTF_BaseAddress+0x504))
#define	GPIOF_DR8R					   *((volatile u32 *)(PORTF_BaseAddress+0x508))
#define	GPIOF_ODR					   *((volatile u32 *)(PORTF_BaseAddress+0x50C))
#define	GPIOF_PUR					   *((volatile u32 *)(PORTF_BaseAddress+0x510))
#define	GPIOF_PDR					   *((volatile u32 *)(PORTF_BaseAddress+0x514))
#define	GPIOF_SLR					   *((volatile u32 *)(PORTF_BaseAddress+0x518))
#define	GPIOF_DEN					   *((volatile u32 *)(PORTF_BaseAddress+0x51C))
#define	GPIOF_LOCK					   *((volatile u32 *)(PORTF_BaseAddress+0x520))
#define GPIOF_CR				       *((volatile u32 *)(PORTF_BaseAddress+0x524))
#define	GPIOF_AMSEL					   *((volatile u32 *)(PORTF_BaseAddress+0x528))
#define	GPIOF_PCTL					   *((volatile u32 *)(PORTF_BaseAddress+0x52C))
#define	GPIOF_ADCCTL				   *((volatile u32 *)(PORTF_BaseAddress+0x530))
#define	GPIOF_DMACTL				   *((volatile u32 *)(PORTF_BaseAddress+0x534))
#define	GPIOF_PeriphID4				   *((volatile u32 *)(PORTF_BaseAddress+0xFD0))
#define	GPIOF_PeriphID5				   *((volatile u32 *)(PORTF_BaseAddress+0xFD4))
#define	GPIOF_PeriphID6				   *((volatile u32 *)(PORTF_BaseAddress+0xFD8))
#define	GPIOF_PeriphID7				   *((volatile u32 *)(PORTF_BaseAddress+0xFDC))
#define	GPIOF_PeriphID0				   *((volatile u32 *)(PORTF_BaseAddress+0xFE0))
#define	GPIOF_PeriphID1				   *((volatile u32 *)(PORTF_BaseAddress+0xFE4))
#define	GPIOF_PeriphID2				   *((volatile u32 *)(PORTF_BaseAddress+0xFE8))
#define	GPIOF_PeriphID3				   *((volatile u32 *)(PORTF_BaseAddress+0xFEC))
#define	GPIOF_PCellID0				   *((volatile u32 *)(PORTF_BaseAddress+0xFF0))
#define	GPIOF_PCellID1				   *((volatile u32 *)(PORTF_BaseAddress+0xFF4))
#define	GPIOF_PCellID2				   *((volatile u32 *)(PORTF_BaseAddress+0xFF8))
#define	GPIOF_PCellID3				   *((volatile u32 *)(PORTF_BaseAddress+0xFFC))


#define RCGCPORT     (*((volatile u32 *)( 0x400FE608 )))
#define PORTHBCTL    (*((volatile u32 *)( 0x400FE06C )))  

/***************************INTCTRL*************************************/
#define NVIC_BaseAddress	0xE000E100



#define	NVIC_ISER0		*((volatile	u32*) (NVIC_BaseAddress + 0x000) )		
#define	NVIC_ISER1		*((volatile	u32*) (NVIC_BaseAddress + 0x004) )     
#define	NVIC_ISER2		*((volatile	u32*) (NVIC_BaseAddress + 0x008) )	  
#define	NVIC_ISER3		*((volatile	u32*) (NVIC_BaseAddress + 0x00C) )	   
#define	NVIC_ISER4		*((volatile	u32*) (NVIC_BaseAddress + 0x010) )	

#define	NVIC_ICER0		*((volatile	u32*) (NVIC_BaseAddress + 0x080) )		
#define	NVIC_ICER1		*((volatile	u32*) (NVIC_BaseAddress + 0x084) )     
#define	NVIC_ICER2		*((volatile	u32*) (NVIC_BaseAddress + 0x088) )	    
#define	NVIC_ICER3		*((volatile	u32*) (NVIC_BaseAddress + 0x08C) )     
#define	NVIC_ICER4		*((volatile	u32*) (NVIC_BaseAddress + 0x090) )	    

#define	NVIC_ISPR0		*((volatile	u32*) (NVIC_BaseAddress + 0x100) )		
#define	NVIC_ISPR1		*((volatile	u32*) (NVIC_BaseAddress + 0x104) )     
#define	NVIC_ISPR2		*((volatile	u32*) (NVIC_BaseAddress + 0x108) )     
#define	NVIC_ISPR3		*((volatile	u32*) (NVIC_BaseAddress + 0x10C) )     
#define	NVIC_ISPR4		*((volatile	u32*) (NVIC_BaseAddress + 0x110) )     

							   

#define NVIC_IPR		*((volatile u32*) (NVIC_BaseAddress + 0x300))
#define NVIC_IPR_30		*((volatile u32*) (NVIC_BaseAddress + 0x330))
#define SCB_AIRCR		*((volatile	u32*) (0xE000ED0C))

/****************************SYSTICK**********************************/
typedef struct
{
	volatile u32 STCTRL  ;
	volatile u32 STRELOAD;
	volatile u32 STCURRENT;
}SysTick_t;


#define  STK  ((SysTick_t*)0xE000E010)



#endif  

